name: vitaplus
description: "Cuidando da sua vitalidade"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  video_player: ^2.9.1
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6 #latest version
  calendar_view: ^1.2.0
  sqflite: ^2.3.3+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/